docker:
  image: yegor256/rultor-image:1.20.0
assets:
  npmrc: maxonfjvipon/secrets#.npmrc
install: |
  pip install git+https://chromium.googlesource.com/external/gyp
  npm install --no-color
  sudo npm install --no-color --global grunt-cli
  npm uninstall --no-color grunt-cli
  npm install --no-color mocha
  pdd -f /dev/null -v
release:
  pre: false
  script: |
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    sed -i "s/0\.0\.0/${tag}/" eo2js/package.json
    sed -i "s/0\.0\.0/${tag}/" eo2js/src/version.js
    sed -i "s/0000-00-00/$(date +%Y-%m-%d)/" eo2js/src/version.js
    sed -i "s/0\.0\.0/${tag}/" eo2js-runtime/package.json
    npm test
    git commit -am "set version to ${tag}"
    chmod 600 ../npmrc
    echo "Dry run:"
    cd eo2js && npm publish --no-color --dry-run --userconfig=../../npmrc
    cd ../eo2js-runtime && npm publish --no-color --dry-run --userconfig=../../npmrc && cd ..
    echo "Publishing:"
    cd eo2js && npm publish --no-color --userconfig=../../npmrc
    (cd ../eo2js-runtime && npm publish --no-color --userconfig=../../npmrc) || (echo "Unpublishing:" && cd ../eo2js && npm unpublish eo2js@${tag} -f --userconfig=../../npmrc)
merge:
  script: |-
    npm test
